name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GEMINAI_API_KEY: ${{ secrets.GEMINAI_API_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y swaks jq

      - name: Build Project
        run: make

      - name: Run Tests
        run: make test

      - name: Clean Up
        run: make clean
