name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Configure Script (if needed)
        run: |
          if [ ! -f ./configure ]; then
              echo "No configure script found, running autoreconf -fi..."
              autoreconf -fi
          else
              echo "Configure script already exists."
          fi

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Run Tests
        run: make check

      - name: Dist Check
        run: make distcheck
