name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Create Build Directory
        run: mkdir -p build

      - name: Configure with CMake
        run: cd build && cmake ..

      - name: Build with CMake
        run: cd build && cmake --build .

      - name: Run Tests
        run: cd build && ctest --output-on-failure
